esphome:
  name: mmwave-presence
  friendly_name: mmwave-presence

# external_components:
#   - source:  github://MattCairns/mr24d11c10-radar-esphome
#     components: [ mr24d11c10 ]
#     refresh: 0s

external_components:
  - source:
      type: local 
      path: components
    components: [ mr24d11c10 ]

esp8266:
  board: d1_mini

# Enable logging
logger:
  baud_rate: 0

# Enable Home Assistant API
api:
  encryption:
    key: "wDOsXOqFTm8daWFTR9jx/8ZmrxhwKlAg8ez4diQV0Gw="

ota:
  password: "974d0d8729d34b540d5d3a61f0c40b84"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Mmwave-Presence Fallback Hotspot"
    password: "D2J8V6Q6E7fp"

captive_portal:

uart:
  id: uartone
  tx_pin: D3
  rx_pin: D4
  baud_rate: 9600

mr24d11c10:
  id: seeedStudioRadar

binary_sensor:  
  - platform: custom
    lambda: |-
      auto uart_component = static_cast<mr24d11c10::Mr24d11c10Component*>(id(seeedStudioRadar));
      return {uart_component->target_present};
    binary_sensors:
      name: "Human Present"

sensor:
- platform: custom
  lambda: |-
    auto uart_component = static_cast<mr24d11c10::Mr24d11c10Component*>(id(seeedStudioRadar));
    return {uart_component->body_movement};

  sensors:
    name: "Radar Activity"
    unit_of_measurement: "%"
    accuracy_decimals: 0

